#!/bin/bash

git config user.email "circleci@pbir"
git config user.name "circleci"
git worktree add book gh-pages
git commit -m "book build at $(git log '--format=format:%H' master -1)"
git push origin gh-pages
