version: 2
jobs:
  build:
    docker:
      - image: circleci/rust:latest
    steps:
      - checkout
      - restore_cache:
          keys:
            - cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
      - run: ./dev/install
      - run: ./dev/ci
      - persist_to_workspace:
          root: .
          paths:
            - build
      - save_cache:
          paths:
            - /usr/local/cargo/registry
            - target
            - ~/.cargo
          key: cargo-cache-{{ arch }}-{{ checksum "Cargo.lock" }}
  deploy:
    docker:
      - image: circleci/rust:latest
    steps:
      - attach_workspace:
          at: .
      - add_ssh_keys:
          fingerprints:
            - "ee:fb:b6:41:8a:df:e8:ad:24:30:a0:ff:42:7f:71:6e"
      - run: ./dev/gh-pages
workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
